name: video_downloader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  fluttertoast: ^8.1.2
  get: ^4.6.5
  http: ^0.13.5
  path_provider: ^2.0.12
  share_plus: ^6.3.1
  validators: ^3.0.0
  youtube_explode_dart: ^1.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

