name: video_downloader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  ffmpeg_kit_flutter_full: ^5.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  fluttertoast: ^8.1.2
  get: ^4.6.5
  html: ^0.15.1
  package_info_plus: ^3.0.3
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  showcaseview: ^2.0.0+1
  url_launcher: ^6.1.10
  validators: ^3.0.0
  webview_flutter: ^4.0.2
  webview_cookie_manager: ^2.0.6
  youtube_explode_dart: ^1.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icon/

